### ISSUE TITLE
64-bit version?

### ISSUE THREAD

**Issue by PoloniumRain** [dechamps/RudeWindowFixer#11]
First of all, i just gotta say.... You're an absolute legend! 

This problem has annoyed me for **SO** many years, since at least Windows Vista. It's been around forever and i can't see MS ever fixing it. I've reported it on the 'Feedback Hub' multiple times but nothing ever happens. Every year or so i'd search for a fix, and this time i found RudeWindowFixer. It works great on Windows 10 and it actually feels weird having the auto-hide Taskbar working properly for once. I keep expecting it to not appear when i move my cursor down.

So anyway, looking at Task Manager i can see that this is 32-bit. Would a 64-bit version be possible? The only reason i ask is that if you were to stop development then there may come a point when 32-bit no longer works. It would be nice to future proof this as much as possible, because like i say, i can't see MS fixing it. So i'll probably be using this for years to come.

**Comment by dechamps** [comment]
The only reason why RudeWindowFixer is 32-bit is because there is no point in having a 64-bit version - it will be bigger and less compatible with older OSes for exactly zero benefit.

It seems extremely unlikely that Windows (or CPU architectures) will break compatibility with 32-bit apps any time soon - that would cause an absolutely staggering number of apps to break.

If that does happen (or if someone wants to use RudeWindowsFixer on, say, Windows ARM), then producing a 64-bit version is trivial - just build it in 64-bit mode. In fact, the GitHub Actions workflow [already does precisely that](https://github.com/dechamps/RudeWindowFixer/blob/5b3795dc3b532ca1a7c46a4dbe76791ebd090c04/.github/workflows/continuous-integration.yml#L10), I'm just not putting the resulting executable on the releases page. You would normally be able to download it directly from the [workflow outputs](https://github.com/dechamps/RudeWindowFixer/actions/workflows/continuous-integration.yml) but sadly GitHub only keeps those for 3 months and the last run is older than that.
