### ISSUE TITLE
Windows7 

### ISSUE THREAD

**Issue by mrx23dot** [dechamps/RudeWindowFixer#14]
I have the same issue on Windows 7, often the taskbar get stuck hidden until I return to Desktop.
Would this help with it?

Latest exe says missing avdapi32.dll
![2024-01-06_110652_H7](https://github.com/dechamps/RudeWindowFixer/assets/4163396/694a5e2c-5b3b-45c4-8a1e-02608b77cb54)

Any other idea if not?

**Comment by dechamps** [comment]
The error is because RudeWindowFixer is using [`EventSetInformation`](https://learn.microsoft.com/en-us/windows/win32/api/evntprov/nf-evntprov-eventsetinformation) for trace logging, but that API was only introduced in Windows 8.

You may be able to get it to work by changing the code to remove trace logging calls, which are not necessary for RudeWindowFixer operation.

I'm not going to fix this as I have zero interest in spending any time supporting an obsolete OS that Microsoft stopped supporting many years ago. I'm afraid you're on your own on this one.

**Comment by mrx23dot** [comment]
The AHK script worked for me instead
https://superuser.com/questions/483453/windows-7-task-bar-stuck-in-hiding-how-to-fix
